name: synth-env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - cudatoolkit=11.8  # specify the version of CUDA Toolkit you need
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pip:
    - ludwig==0.7.4
    - plotly==5.15.0
    - scikit-learn==1.1.3
    - sdv==1.2.0
    - jupyterlab==3.5.3
    - pandas==2.0.3
    - torchmetrics==0.11.4